---
- hosts: ubuntu_focal
  roles:
    - role: grog.package
    - role: snap
    - role: gnome_config
      become: yes
      become_user: "{{ username }}"
    - role: mullvad_vpn
    - role: libvirt
    - role: ruby
