---
# GNOME desktop modifications

- name: Desktop, show weekday in clock
  command: gsettings set org.gnome.desktop.interface clock-show-weekday true

- name: Desktop, show battery percent
  command: gsettings set org.gnome.desktop.interface show-battery-percentage true