---
# GNOME keybindings

- name: Keybindings, launch Firefox (ctrl-alt-w)
  command: gsettings set org.gnome.settings-daemon.plugins.media-keys www "['<Primary><Alt>w']"

- name: Keybindings, launch Thunderbird (ctrl-alt-e)
  command: gsettings set org.gnome.settings-daemon.plugins.media-keys email "['<Primary><Alt>e']"

- name: Keybindings, launch home folder (ctrl-alt-f)
  command: gsettings set org.gnome.settings-daemon.plugins.media-keys home "['<Primary><Alt>f']"

- name: Keybindings, rotate screen (ctrl-alt-r)
  command: gsettings set org.gnome.mutter.keybindings rotate-monitor "['XF86RotateWindows', '<Control><Alt>r']"

# see https://unix.stackexchange.com/a/558857 to add more custom keybindings
- name: Custom Keybindings
  shell: |
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding "<Primary><Alt>g"
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "gedit"
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "Gedit"